
package br.com.caelum.estoque.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EstoqueWS", targetNamespace = "http://ws.estoque.caelum.com.br/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EstoqueWS {


    /**
     * 
     * @param filtros
     * @return
     *     returns br.com.caelum.estoque.cliente.Item
     */
    @WebMethod(operationName = "TodosOsItens")
    @WebResult(name = "item", targetNamespace = "http://ws.estoque.caelum.com.br/", partName = "item")
    @Action(input = "http://ws.estoque.caelum.com.br/EstoqueWS/TodosOsItensRequest", output = "http://ws.estoque.caelum.com.br/EstoqueWS/TodosOsItensResponse")
    public Item todosOsItens(
        @WebParam(name = "filtros", targetNamespace = "http://ws.estoque.caelum.com.br/", partName = "filtros")
        Filtros filtros);

    /**
     * 
     * @param item
     * @param tokenUsuario
     * @throws AutorizacaoFault
     */
    @WebMethod(operationName = "CadastrarItem")
    @Action(input = "http://ws.estoque.caelum.com.br/EstoqueWS/CadastrarItemRequest", output = "http://ws.estoque.caelum.com.br/EstoqueWS/CadastrarItemResponse", fault = {
        @FaultAction(className = AutorizacaoFault.class, value = "http://ws.estoque.caelum.com.br/EstoqueWS/CadastrarItem/Fault/AutenticacaoException")
    })
    public void cadastrarItem(
        @WebParam(name = "tokenUsuario", targetNamespace = "http://ws.estoque.caelum.com.br/", header = true, partName = "tokenUsuario")
        TokenUsuario tokenUsuario,
        @WebParam(name = "item", targetNamespace = "http://ws.estoque.caelum.com.br/", mode = WebParam.Mode.INOUT, partName = "item")
        Holder<Item> item)
        throws AutorizacaoFault
    ;

}
